kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-test
  namespace: environment
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
---
kind: Pod
apiVersion: v1
metadata:
  name: nfs-test-pod
  namespace: environment
spec:
  containers:
  - name: nfs-test-pod
    image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-test-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-test-pvc
      persistentVolumeClaim:
        claimName: nfs-test
