#!/bin/bash

rpm_dir="$1"
[ $(echo ${rpm_dir}|grep /$ &>/dev/null;echo $?) -eq 0 ] && rpm_dir="$(echo ${rpm_dir}|sed 's/^\(.*\)\/$/\1/g')"
[ "X${rpm_dir}" == "X" ] && rpm_dir='.'

# 分离包名
for f in $(ls ${rpm_dir}/*.rpm)
do
  # 无版本号
  #rpm_name_no_version=$(echo $f|awk -F/ '{print $NF}'|sed 's/\(.*\)-[0-9].*-.*el7.*rpm/\1/g')
  # 保留版本号
  rpm_name=$(echo $f|awk -F/ '{print $NF}'|sed 's/\.rpm//g')
  # 检测同版本rpm包
  [ $(rpm -q ${rpm_name} &>/dev/null;echo $?) -eq 0 ] && rm -f $f
  # 检测不同版本rpm包
  #[ $(rpm -qa|grep "^${rpm_name_no_version}-[0-9].*-.*el7" &>/dev/null;echo $?) -eq 0 ] && rm -f $f
done

exit 0
